package nutrimate;

import javax.swing.table.DefaultTableModel;
import java.util.List;

public class KalkulatorFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName());

    /**
     * Creates new form KalkulatorFrame
     */
    public KalkulatorFrame() {
        initComponents();
        tampilkanTabelMakanan();
    }
    public void tampilkanTabelMakanan() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Makanan");
    model.addColumn("Nama Makanan");
    model.addColumn("Kalori (Kcal)");
    model.addColumn("Protein (g)");
    model.addColumn("Karbohidrat (g)");
    model.addColumn("Lemak (g)");
    
    try {
        MakananDAO dao = new MakananDAO();
        List<Makanan> daftarMakanan = dao.getAllMakanan(); 
        
        for (Makanan m : daftarMakanan) {
            model.addRow(new Object[]{
                m.getIdMakanan(),
                m.getNamaMakanan(),
                m.getKalori(),
                m.getProtein(),
                m.getKarbohidrat(),
                m.getLemak()
            });
        }
        
        // MASUKKAN KE SINI: Set model dipanggil TEPAT setelah data selesai di-looping
        tblMakanan.setModel(model); 
        
    } catch (Exception e) {
        System.out.println("Gagal memuat data ke tabel: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBerat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTinggi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbJenisKelamin = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblHasilKalori = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMakanan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Berat Badan (kg)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtBerat.setText(" ");
        getContentPane().add(txtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel2.setText("Tinggi Badan (cm)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtTinggi.setText(" ");
        txtTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinggiActionPerformed(evt);
            }
        });
        getContentPane().add(txtTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel3.setText("Berat Badan (kg)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setText("Umur");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtUmur.setText(" ");
        txtUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmurActionPerformed(evt);
            }
        });
        getContentPane().add(txtUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan", " " }));
        getContentPane().add(cbJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        btnHitung.setText("Hitung Gizi");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        lblHasilKalori.setText("Kebutuhan Kalori: - Kcal");
        getContentPane().add(lblHasilKalori, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel7.setText("Katalog Gizi Makanan (Database)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        tblMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMakanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinggiActionPerformed

    private void txtUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmurActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
        // 1. Mengambil data angka yang diketik user di form input
        double berat = Double.parseDouble(txtBerat.getText().trim());
        double tinggi = Double.parseDouble(txtTinggi.getText().trim());
        int umur = Integer.parseInt(txtUmur.getText().trim());
        String jk = cbJenisKelamin.getSelectedItem().toString();
        
        double bmr = 0;
        
        // 2. Rumus kalkulator kalori (Harris-Benedict)
        if (jk.equals("Laki-laki")) {
            bmr = 66.5 + (13.75 * berat) + (5.003 * tinggi) - (6.75 * umur);
        } else {
            bmr = 655.1 + (9.563 * berat) + (1.850 * tinggi) - (4.676 * umur);
        }
        
        // 3. Memasukkan hasil hitungan ke label visual
        lblHasilKalori.setText("Kebutuhan Kalori: " + Math.round(bmr) + " Kcal");
        
    } catch (NumberFormatException e) {
        // Jika user mengosongkan input atau mengetik huruf/tulisan bukan angka
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Mohon masukkan data angka yang valid!", 
                "Input Salah", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KalkulatorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cbJenisKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHasilKalori;
    private javax.swing.JTable tblMakanan;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtTinggi;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
